# Generated by Django 4.2.6 on 2023-11-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
