# Generated by Django 4.2.6 on 2023-11-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0051_remove_recipe_allergens_recipeallergens'),
        ('accounts', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_created_recipes',
            field=models.ManyToManyField(blank=True, related_name='created_by', to='recipes.recipe'),
        ),
    ]
