# Generated by Django 4.2.6 on 2023-11-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0051_remove_recipe_allergens_recipeallergens'),
        ('accounts', '0005_alter_user_favorite_recipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, default=[], related_name='user_favorite_recipes', to='recipes.recipe'),
        ),
    ]
