# Generated by Django 4.2.6 on 2023-11-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_favorite_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
