# Generated by Django 4.2.6 on 2023-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_category_recipe_origin_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='', help_text='Each ingredients must be separated by a comma.', max_length=255),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
