# Generated by Django 4.2.6 on 2023-10-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, help_text='This value is calculated automatically, not input require here.', max_length=20, null=True),
        ),
    ]
