# Generated by Django 4.2.6 on 2023-10-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_cooking_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('ml - milliliter', 'ml - Milliliter'), ('fl oz - fluid ounce', 'fl oz - Fluid Ounce'), ('tbsp - tablespoon', 'tbsp - Tablespoon'), ('tsp - teaspoon', 'tsp - Teaspoon'), ('L - liter', 'L - Liter'), ('pt - pint', 'pt - Pint'), ('g - gram', 'g - Gram'), ('oz - ounce', 'oz - Ounce'), ('lb - pound', 'lb - Pound'), ('kg - kilogram', 'kg - Kilogram'), ('unit', 'Unit'), ('units', 'Units')], max_length=30)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
    ]
