# Generated by Django 4.2.6 on 2023-10-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_recipe_ingredients_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='', help_text='Each ingredients must be separated by a comma.', max_length=255),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
