# Generated by Django 4.2.6 on 2023-10-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipe_ingredients_delete_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_instructions',
            field=models.TextField(),
        ),
    ]
