# Generated by Django 4.2.6 on 2023-10-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_rename_pic_recipe_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='picture',
            new_name='pic',
        ),
    ]
