# Generated by Django 4.2.6 on 2023-10-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_rename_picture_recipe_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty',
        ),
    ]
