# Generated by Django 4.2.6 on 2023-10-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_remove_recipe_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCookingInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('step_instruction', models.CharField(max_length=500)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_instructions', to='recipes.recipe')),
            ],
        ),
    ]
