# Generated by Django 4.2.6 on 2023-10-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_recipecookinginstructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
