# Generated by Django 4.2.6 on 2023-10-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_recipecookinginstructions_instruction_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecookinginstructions',
            name='instruction_number',
        ),
        migrations.CreateModel(
            name='RecipeToolsNeeded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooking_tool_name', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tools', to='recipes.recipe')),
            ],
        ),
    ]
