# Generated by Django 4.2.6 on 2023-10-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_remove_recipecookinginstructions_instruction_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecookinginstructions',
            options={'verbose_name': 'Recipe cooking instructions', 'verbose_name_plural': 'Recipe cooking instructions'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name': 'Recipe ingredients', 'verbose_name_plural': 'Recipe Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipetoolsneeded',
            options={'verbose_name': 'Recipe required tools', 'verbose_name_plural': 'Recipe required tools'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='number_portions',
            field=models.IntegerField(default=4, help_text='Indicates how many servings this recipe is for'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='special_note',
            field=models.TextField(blank=True),
        ),
    ]
