# Generated by Django 4.2.6 on 2023-10-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_alter_recipecookinginstructions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='number_portions',
            field=models.IntegerField(default=4, help_text='Indicates how many servings this recipe is for'),
        ),
    ]
