# Generated by Django 4.2.6 on 2023-10-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_rename_name_recipe_recipe_name_recipe_creator_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipesimilarcomplementary',
            options={'verbose_name': 'Similar/complementary recipe', 'verbose_name_plural': 'Similar/complementary recipe'},
        ),
        migrations.AlterField(
            model_name='recipesimilarcomplementary',
            name='complementary_recipe_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
