# Generated by Django 4.2.6 on 2023-10-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_alter_recipesimilarcomplementary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergens',
            field=models.CharField(default='None', help_text='Indicate all allergens contained in this recipe', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='estimated_total_cost',
            field=models.FloatField(default=0, help_text='Estimated total cost in dollar $'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_category',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('baked', 'Baked'), ('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('condiment', 'Condiment'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drink/cocktail', 'drink/cocktail'), ('fish', 'Fish'), ('fruit', 'Fruit'), ('holiday', 'holiday'), ('juice', 'Juice'), ('lunch', 'Lunch'), ('meat', 'meat'), ('pasta', 'Pasta'), ('salad', 'Salad'), ('sandwhich', 'Sandwhich'), ('sauce', 'Sauce'), ('seafood', 'Seafood'), ('side', 'Side'), ('smoothie/shake', 'smoothie/shake'), ('snack', 'Snack'), ('soup', 'Soup'), ('vegan', 'Vegan'), ('vegetable', 'vegetable'), ('vegetarian', 'Vegetarian')], default='other', help_text='Select the category associated to this recipe', max_length=30),
        ),
    ]
