# Generated by Django 4.2.6 on 2023-10-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0032_recipe_allergens_recipe_estimated_total_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='estimated_total_cost',
            new_name='recipe_estimated_cost',
        ),
    ]
