# Generated by Django 4.2.6 on 2023-10-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0033_rename_estimated_total_cost_recipe_recipe_estimated_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(default='', help_text='Shortened URL for sharing', max_length=150),
        ),
    ]
