# Generated by Django 4.2.6 on 2023-10-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_recipe_short_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='short_url',
            new_name='recipe_url',
        ),
    ]
