# Generated by Django 4.2.6 on 2023-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0036_alter_recipe_recipe_url_recipecomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecomments',
            options={'verbose_name': 'Recipe comment(s)', 'verbose_name_plural': 'Recipe comment(s)'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_estimated_cost',
            field=models.FloatField(default=10, help_text='Estimated total cost in dollar $'),
        ),
    ]
