# Generated by Django 4.2.6 on 2023-10-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0037_alter_recipecomments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_url',
            field=models.CharField(help_text='Recipe URL for sharing', max_length=150),
        ),
    ]
