# Generated by Django 4.2.6 on 2023-10-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0038_alter_recipe_recipe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_url',
            field=models.CharField(blank=True, help_text='Recipe URL for sharing', max_length=150),
        ),
    ]
