# Generated by Django 4.2.6 on 2023-10-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0039_alter_recipe_recipe_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_url',
        ),
    ]
