# Generated by Django 4.2.6 on 2023-10-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0041_recipetoolsneeded_cooking_tool_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='possible_substitute',
            field=models.CharField(blank=True, help_text='Optional - Indicate here which ingredient could replace the one mentionned if not available', max_length=100),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='substitue_special_note',
            field=models.CharField(max_length=300, blank=True, help_text='This field is optional'),
        ),
    ]
