# Generated by Django 4.2.6 on 2023-10-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0042_recipeingredients_possible_substitute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesimilarcomplementary',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='recipes'),
        ),
    ]
