# Generated by Django 4.2.6 on 2023-10-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0043_recipesimilarcomplementary_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesimilarcomplementary',
            old_name='pic',
            new_name='similar_recipe_pic',
        ),
    ]
