# Generated by Django 4.2.6 on 2023-11-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0047_alter_recipe_origin_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesimilarcomplementary',
            old_name='complementary_recipe_link',
            new_name='complementary_recipe_link_unsigned_users',
        ),
        migrations.AddField(
            model_name='recipesimilarcomplementary',
            name='complementary_recipe_link_signed_users',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
