# Generated by Django 4.2.6 on 2023-11-06 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0048_rename_complementary_recipe_link_recipesimilarcomplementary_complementary_recipe_link_unsigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='creator_name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
