# Generated by Django 4.2.6 on 2023-11-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0049_remove_recipe_creator_name_recipe_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_instructions',
        ),
    ]
