# Generated by Django 4.2.6 on 2023-11-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0050_remove_recipe_cooking_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='allergens',
        ),
        migrations.CreateModel(
            name='RecipeAllergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_allergens', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Recipe allergen',
                'verbose_name_plural': 'Recipe Allergen',
            },
        ),
    ]
