# Generated by Django 4.2.6 on 2023-11-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0053_alter_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
